# Generated by Django 4.2.16 on 2024-10-06 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second_game', '0004_remove_round_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_win_rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
