# Generated by Django 5.1.1 on 2024-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
