# Generated by Django 4.2.16 on 2024-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
