# Generated by Django 4.2.16 on 2024-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_user_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sentInvite',
            field=models.BooleanField(default=False),
        ),
    ]
