# Generated by Django 4.2.16 on 2024-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_user_sentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s_game_option',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
    ]
