services:
  backend:
    image: backend
    container_name: backend
    build: ./requirements/backend
    volumes:
      - backend_code:/app



volumes:
  backend_code:
    driver: local 
    driver_opts:
      type: none
      device: ./requirements/backend/backend_app/ 
      o: bind

