# Generated by Django 4.2.16 on 2024-09-21 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('player_x', models.IntegerField(default=0)),#
                # ('player_y', models.IntegerField(default=175)),#
                # ('opponent_x', models.IntegerField(default=785)),#
                # ('opponent_y', models.IntegerField(default=175)),#
                # ('ball_x', models.IntegerField(default=400)),#
                # ('ball_y', models.IntegerField(default=250)),#
                # ('ball_speed_x', models.IntegerField(default=-5)),#
                # ('ball_speed_y', models.IntegerField(default=5)),#
                # ('scored', models.BooleanField(default=True)),#
                ('typeOfMatch', models.CharField(default='rg', max_length=2)),
                ('scorePlayer', models.IntegerField(default=0)),
                ('scoreOpponent', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberParticipants', models.IntegerField(default=4)),
                ('finished', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('exiters', models.ManyToManyField(related_name='exited_tournaments', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ManyToManyField(related_name='in_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('finished', models.BooleanField(default=False)),
                ('matches', models.ManyToManyField(to='Game.match')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
