# Generated by Django 4.2.16 on 2024-10-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_game', '0003_rename_player1_sgame_p1_rename_player2_sgame_p2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='round_number',
        ),
    ]
