services:
  backend:
    image: backend
    container_name: backend
    build: ./requirements/backend
    expose:
      - 8000
    networks:
      - netw
    env_file:
      - .env
    volumes:
      - media:/app/backend/media


  frontend:
    image: frontend
    container_name: frontend
    build: ./requirements/frontend
    ports:
      - "5173:5173"
    networks:
      - netw

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 5000:80
    volumes:
      - media:/home/app/web/staticfiles
    depends_on:
      - backend
      - frontend
    networks:
      - netw
  
  db:
    container_name: db
    image: postgres:15.8-alpine3.20
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    env_file:
      - .env
    networks:
      - netw




volumes:
  media:

networks:
  netw:
