services:
  backend:
    image: backend
    container_name: backend
    build: ./requirements/backend
    networks:
      - netw
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
    volumes:
      - media:/app/backend/media



  nginx:
    build: 
      context: ./requirements/nginx/
      args:
          - BACKEND_HOST=${BACKEND_HOST}
          - URL_42=${URL_42}
    container_name: nginx
    image : nginx
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - media:/home/app/web/staticfiles
      # - frontend:/app
    depends_on:
      - backend
    networks:
      - netw
  
  db:
    container_name: db
    image: postgres:15.8-alpine3.20
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - netw


volumes:
  media:
  postgres_data:
  # frontend:
  backend:
    name: db_vol
    driver: local
    driver_opts:
      type: bind
      device: $(pwd)/tr-docker/src/backend/app
      o: bind
networks:
  netw:
