services:
  backend:
    image: backend
    container_name: backend
    build: ./requirements/backend
    volumes:
      - backend_code:/app
    ports:
      - "8000:8000"
    networks:
      - netw



  frontend:
    image: frontend
    container_name: frontend
    build: ./requirements/frontend
    ports:
      - "5173:5173"
    volumes:
      - frontend_code:/app
    networks:
      - netw




volumes:
  backend_code:
    driver: local 
    driver_opts:
      type: none
      device: /goinfre/${USER}/tr-docker/src/requirements/backend/app/ 
      o: bind

  frontend_code:
    driver: local
    driver_opts:
      type: none
      device: /goinfre/${USER}/tr-docker/src/requirements/frontend/app/
      o: bind

networks:
  netw:
