# Generated by Django 4.2.16 on 2024-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserActions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitequeue',
            name='status',
            field=models.CharField(choices=[('P', 'accept'), ('A', 'accept'), ('D', 'decline')], default='P', max_length=1),
        ),
    ]
